### ISSUE TITLE
Support new 'Remove String Approvals' API endpoint

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-go#68]
Crowdin has recently introduced a new [Remove String Approvals](https://support.crowdin.com/developer/api/v2/#tag/String-Translations/operation/api.projects.approvals.deleteMany) API endpoint that allows you to remove approvals for a specific string in a project for all languages in one request.

Also, the [Delete String Translations](https://support.crowdin.com/developer/api/v2/#tag/String-Translations/operation/api.projects.translations.deleteMany) API endpoint has been updated: `languageId` parameter is now optional.

These changes are not yet supported in the Crowdin API clients and we need to add support for them.

**Comment by SufyaanKhateeb** [comment]
I would like to work on this please.

**Comment by SufyaanKhateeb** [comment]
For the Delete string Translations can I change the signature of the function to take in languageID as a string pointer for managing the optional parameter or do we need this function for keeping backward compatibility?
`DeleteStringTranslations(ctx context.Context, projectID, stringID int, languageID *string)`

Or we could also just pass in an empty string for the languageID to denote a query without languageID?

**Comment by andrii-bodnar** [comment]
@SufyaanKhateeb I believe you can change the signature. We'll add a warning about this in the release notes.
